spring:
  datasource:
    url: jdbc:sqlserver://javasqldemo.database.windows.net:1433;database=javasessionsqldemo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

   
    username: sqldemov1
    password: Welcome@96
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


