spring:
  datasource:
    url: jdbc:sqlserver://javatechdemo.database.windows.net:1433;database=javatechdemo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    
    username: javatechdb
    password: Welcome@96
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


